version: "3.9"

services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:123456@db:5432/techntrove?schema=public
      JWT_SECRET: ${jwt_secret}
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15
    container_name: postgres_db_2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: techntrove
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: